BEGIN;
DELETE FROM groups;
DELETE FROM group_users;

INSERT INTO groups(id, name) VALUES(3, 'チームC');
INSERT INTO group_users(group_id, user_id) VALUES(3, 13);
INSERT INTO group_users(group_id, user_id) VALUES(3, 48);
INSERT INTO group_users(group_id, user_id) VALUES(3, 4);
INSERT INTO group_users(group_id, user_id) VALUES(3, 28);
INSERT INTO groups(id, name) VALUES(4, 'チームD');
INSERT INTO group_users(group_id, user_id) VALUES(4, 7);
INSERT INTO group_users(group_id, user_id) VALUES(4, 65);
INSERT INTO group_users(group_id, user_id) VALUES(4, 32);
INSERT INTO group_users(group_id, user_id) VALUES(4, 61);
INSERT INTO groups(id, name) VALUES(5, 'チームE');
INSERT INTO group_users(group_id, user_id) VALUES(5, 22);
INSERT INTO group_users(group_id, user_id) VALUES(5, 57);
INSERT INTO group_users(group_id, user_id) VALUES(5, 49);
INSERT INTO group_users(group_id, user_id) VALUES(5, 45);
INSERT INTO groups(id, name) VALUES(6, 'チームF');
INSERT INTO group_users(group_id, user_id) VALUES(6, 51);
INSERT INTO group_users(group_id, user_id) VALUES(6, 35);
INSERT INTO group_users(group_id, user_id) VALUES(6, 18);
INSERT INTO group_users(group_id, user_id) VALUES(6, 29);
INSERT INTO groups(id, name) VALUES(7, 'チームG');
INSERT INTO group_users(group_id, user_id) VALUES(7, 26);
INSERT INTO group_users(group_id, user_id) VALUES(7, 63);
INSERT INTO group_users(group_id, user_id) VALUES(7, 59);
INSERT INTO group_users(group_id, user_id) VALUES(7, 5);
INSERT INTO groups(id, name) VALUES(8, 'チームH');
INSERT INTO group_users(group_id, user_id) VALUES(8, 41);
INSERT INTO group_users(group_id, user_id) VALUES(8, 58);
INSERT INTO group_users(group_id, user_id) VALUES(8, 1);
INSERT INTO group_users(group_id, user_id) VALUES(8, 10);
INSERT INTO groups(id, name) VALUES(9, 'チームI');
INSERT INTO group_users(group_id, user_id) VALUES(9, 27);
INSERT INTO group_users(group_id, user_id) VALUES(9, 33);
INSERT INTO group_users(group_id, user_id) VALUES(9, 21);
INSERT INTO group_users(group_id, user_id) VALUES(9, 40);
INSERT INTO groups(id, name) VALUES(10, 'チームJ');
INSERT INTO group_users(group_id, user_id) VALUES(10, 64);
INSERT INTO group_users(group_id, user_id) VALUES(10, 62);
INSERT INTO group_users(group_id, user_id) VALUES(10, 15);
INSERT INTO group_users(group_id, user_id) VALUES(10, 9);
INSERT INTO groups(id, name) VALUES(11, 'チームK');
INSERT INTO group_users(group_id, user_id) VALUES(11, 17);
INSERT INTO group_users(group_id, user_id) VALUES(11, 34);
INSERT INTO group_users(group_id, user_id) VALUES(11, 6);
INSERT INTO group_users(group_id, user_id) VALUES(11, 25);
INSERT INTO groups(id, name) VALUES(12, 'チームL');
INSERT INTO group_users(group_id, user_id) VALUES(12, 38);
INSERT INTO group_users(group_id, user_id) VALUES(12, 3);
INSERT INTO group_users(group_id, user_id) VALUES(12, 53);
INSERT INTO groups(id, name) VALUES(13, 'チームM');
INSERT INTO group_users(group_id, user_id) VALUES(13, 11);
INSERT INTO group_users(group_id, user_id) VALUES(13, 16);
INSERT INTO group_users(group_id, user_id) VALUES(13, 36);
INSERT INTO group_users(group_id, user_id) VALUES(13, 47);
INSERT INTO groups(id, name) VALUES(14, 'チームN');
INSERT INTO group_users(group_id, user_id) VALUES(14, 30);
INSERT INTO group_users(group_id, user_id) VALUES(14, 67);
INSERT INTO group_users(group_id, user_id) VALUES(14, 44);
INSERT INTO group_users(group_id, user_id) VALUES(14, 68);
INSERT INTO groups(id, name) VALUES(15, 'チームO');
INSERT INTO group_users(group_id, user_id) VALUES(15, 20);
INSERT INTO group_users(group_id, user_id) VALUES(15, 46);
INSERT INTO group_users(group_id, user_id) VALUES(15, 12);
INSERT INTO group_users(group_id, user_id) VALUES(15, 60);
INSERT INTO groups(id, name) VALUES(16, 'チームP');
INSERT INTO group_users(group_id, user_id) VALUES(16, 52);
INSERT INTO group_users(group_id, user_id) VALUES(16, 31);
INSERT INTO group_users(group_id, user_id) VALUES(16, 55);
INSERT INTO group_users(group_id, user_id) VALUES(16, 23);

INSERT INTO groups(id, name) VALUES(17, 'チームA');
INSERT INTO group_users(group_id, user_id) VALUES(17, 70);
INSERT INTO group_users(group_id, user_id) VALUES(17, 69);
INSERT INTO group_users(group_id, user_id) VALUES(17, 72);
INSERT INTO group_users(group_id, user_id) VALUES(17, 76);

INSERT INTO groups(id, name) VALUES(18, 'チームB');
INSERT INTO group_users(group_id, user_id) VALUES(18, 73);
INSERT INTO group_users(group_id, user_id) VALUES(18, 71);
INSERT INTO group_users(group_id, user_id) VALUES(18, 74);
INSERT INTO group_users(group_id, user_id) VALUES(18, 75);

INSERT INTO groups(id, name) VALUES(1, 'チームQ');
INSERT INTO group_users(group_id, user_id) VALUES(1, 19);
INSERT INTO group_users(group_id, user_id) VALUES(1, 37);
INSERT INTO group_users(group_id, user_id) VALUES(1, 24);
INSERT INTO group_users(group_id, user_id) VALUES(1, 14);

INSERT INTO groups(id, name) VALUES(2, 'チームR');
INSERT INTO group_users(group_id, user_id) VALUES(2, 56);
INSERT INTO group_users(group_id, user_id) VALUES(2, 43);
INSERT INTO group_users(group_id, user_id) VALUES(2, 50);
INSERT INTO group_users(group_id, user_id) VALUES(2, 42);

COMMIT;
